### ISSUE TITLE
能将mongo数据库转为mysql数据库吗

### ISSUE THREAD

**Issue by mlb0925** [criyle/go-judger-demo#7]
能将mongo数据库转为mysql数据库吗

**Comment by criyle** [comment]
如果需要修改数据库实现，可以修改 demoserver/db.go 来实现。

本项目仅提供一个 https://github.com/criyle/go-judge 的 demo 实现，并不能用作生产环境。

**Comment by mlb0925** [comment]
谢谢 ，不知道用那个类实现
